name: mqtt-s7-ha-addon
version: 1.0.4
slug: s7tomqtt
url: https://github.com/p0nch00/mqtt-s7-ha-addon
description: Connect S7 to MQTT
boot: auto
host_network: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
